### ISSUE TITLE
NullPointerException when running InspectClojureSensor.buildKibitLintProperties

### ISSUE THREAD

**Issue by molst** [zmsp/sonar-clojure#1]
Howdi!

Seems like there is a problem splitting the kibit output. When I run kibit without sonar-runner I get no output, which I suppose means success. Maybe an empty string as kibit output gives null as string split output, which is currently not handled gracefully.

I'm running kibit 0.1.2, eastwood 0.2.2 and Clojure 1.7.0 and successfully connects to the sonar server.

Regards,
Marcus @Intelliplan

●▬▬▬▬▬▬▬▬▬● Running Kibit ●▬▬▬▬▬▬▬▬▬●
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 47.382s
Final Memory: 13M/227M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
    at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
    at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
    at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
    at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
    at org.sonar.runner.api.Runner.execute(Runner.java:100)
    at org.sonar.runner.Main.executeTask(Main.java:70)
    at org.sonar.runner.Main.execute(Main.java:59)
    at org.sonar.runner.Main.main(Main.java:53)
Caused by: java.lang.NullPointerException
    at org.sonar.plugins.clojure.InspectClojureSensor.buildKibitLintProperties(InspectClojureSensor.java:137)
    at org.sonar.plugins.clojure.InspectClojureSensor.analyse(InspectClojureSensor.java:111)
    at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
    at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:258)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:253)
    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
    at org.sonar.batch.bootstrap.GlobalContainer.executeAnalysis(GlobalContainer.java:153)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:110)
    at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
    at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)

**Comment by molst** [comment]
I just verified that kibit is just returning exit code 0 and no other output.

**Comment by zmsp** [comment]
Just pushed 0cd92dfc64b4af4fda39c3451836b74a9696cf9d  fixing it. Thanks for creating the issue.

**Comment by molst** [comment]
Thanks, however, the core problem is still there. See this line
https://github.com/zmsp/sonar-clojure/blob/master/src/main/java/org/sonar/plugins/clojure/InspectClojureSensor.java#L136
When kibit exits successfully there is no output, so there is no "At" to look for when splitting the string. This will always lead to a null pointer exception in the positive case.
Test it on some simple code that is perfect according to kibit.

Regards,
Marcus

**Comment by n2o** [comment]
You might have fixed it, but you did not release a new jar file ;-) it would be nice to have the latest jar files in your releases.

**Comment by zmsp** [comment]
The concerns on this issue are fixed. 

It was way overdue. 
Thanks.
